l=[10,12,14,50,'hi']
print(l.count(10))
print(l.index('hi'))
print(l.remove(10))
l1=[12,90,30]
print(l.extend(l1))
print(l.insert(1,'hello'))
print(l)
print(l.pop(1))
print(l)
l.append('hhhhhhh')
print("apended list:",l)
a=l.copy()
print(a)
l1.sort()
print(l1)
