s = "bangalore weather is nice"

print(s.capitalize())
print(s.title())
print(s.isspace())
print(s.count("a"))
print(s.find("o"))
print(s.split())
print(s.isalnum())
print(s.isalpha())
print(s.islower())
print(s.isupper())
print(s.upper())
print(s.lower())
print(s.index("g"))
print(s.replace("nice","awesome"))
print("@".join(s))
print(s.endswith("e"))
print(s.startswith("B"))
